config/routes.rb
Rails.application.routes.draw do

  get 'dashboard', :to => 'dashboards#dashboard'

  get 'feedback/completed', :to => 'feedbacks#completed'
  resources :feedbacks
  get 'privacy_policy', :to => 'static_pages#privacy_policy'
  get 'static/map_data/', to: 'static_data#map_data'
  get 'static/captcha_key/', to: 'static_data#captcha_key'
  get 'static/eula/', to: 'static_data#get_eula'

  delete 'measurements/:id', to: 'measurements#destroy', as: 'measurements/destroy'

  post 'measurements/group/', to: 'measurements#create_group', as: 'measurements/group/create'
  put 'measurements/group/:id', to: 'measurements#update_group', as: 'measurements/group/update'
  delete 'measurements/group/:id', to: 'measurements#destroy_group', as: 'measurements/group/destroy'

  post 'terms_and_conditions/accept'
  get 'terms_and_conditions/has_accepted'
  get 'terms_and_conditions/show', :to => 'static_pages#terms_and_conditions'
  get 'terms_and_conditions', to: 'terms_and_conditions#show'

  devise_scope :user do
    get 'registration/completed/:id', to: 'users/registrations#completed', as: 'registration/completed'
    get 'profile', to: 'profiles#show'
    patch 'profile_picture', to: 'profiles#set_profile_picture'
  end

  resources :ratings
  get 'locations/mine', to: 'locations#my_locations'
  resources :locations

  resources :notifications
  resources :notification_templates

  resources :preferences
  patch 'preferences/user', to: 'preferences#update', as: 'user/preferences/update'

  resources :businesses
  post 'business/tag', to: 'businesses#create_tag', as: 'business/tag/create'
  delete 'business/tag', to: 'businesses#destroy_tag', as: 'business/tag/destroy'

  resources :pictures
  get 'landing_page/index', as: 'landing_page'

  resources :addresses
  devise_for :users, :controllers => {
      :confirmations => 'users/confirmations',
      :passwords => 'users/passwords',
      :registrations => 'users/registrations',
      :sessions => 'users/sessions',
      :unlocks => 'users/unlocks',
  }, :format => false
  resources :promo_codes
  resources :tags
  resources :quotes

  get 'purchases/completed', to: 'purchases#completed', :format => false
  get 'purchases/packages', to: 'purchases#list_packages'
  resources :purchases, :format => false, only: [:index, :new, :create, :show]

  get 'projects/mine', to: 'projects#my_projects', as: 'projects_mine'
  resources :projects, :format => false

  get 'estimates/mine', to: 'estimates#my_estimates', as: 'estimates_mine'
  resources :estimates

  resources :landing_page
  resources :quantifiers
  require 'resque-history/server'

  post 'projects/:id/spam' => 'projects#report_as_spam', as: 'project_report_as_spam'
  patch 'projects/:id/publish' => 'projects#publish', as: 'publish_project'
  patch 'projects/:id/cancel' => 'projects#cancel', as: 'cancel_project'
  patch 'projects/:id/accept/:estimate_id' => 'projects#accept_quote', as: 'accept_quote'
  get 'projects/search/lat/:lat/lng/:lng', to: 'projects#search', as: 'summaries_search', constraints: {lat: /[-\d.]*/, lng: /[-\d.]*/ }
  post 'projects/:id/tag', to: 'projects#create_tag', as: 'project/tag/create'
  delete 'project/:id/tag', to: 'projects#destroy_tag', as: 'project/tag/destroy'

  get 'tags/find_like_name/:name', to: 'tags#find_like_name', as: 'find_like_name'

  get 'ratings/get_business_ratings/:business_id', to: 'ratings#get_business_ratings'

  patch 'promo_code/:id/cancel' => 'promo_codes#cancel', as: 'cancel_promotion'
  get 'validate_promo_code', to: 'promo_codes#validate_promo_code', :format => false

  get 'user_landing_page', to: 'projects#index'
  get 'business_landing_page', to: 'projects#index'
  get 'admin_landing_page', to: 'tags#index'

  get 'account_search', to: 'business_centre#account_search'
  get 'business_search', to: 'business_centre#business_search'

  root 'landing_page#index'

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  public_routes = []
  user_routes = [:create]
  business_routes = [:create_tag, :destroy_tag, :update]

  skip_before_action :authenticate_user!, :only => public_routes
  skip_before_action :admin_only, :only => public_routes.concat(user_routes).concat(business_routes).concat(user_routes).concat(business_routes)
  before_action :user_only, :only => user_routes
  before_action :business_only, :only => business_routes

  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = CreationHelper.create_business(params)
    @business.user = current_user

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render json: BusinessDTO.instance_to_hash(@business), status: :created}
      else
        logger.warn "Trying to create business{#{@business.inspect}} resulted in errors: #{@business.errors.full_messages}"
        errors =  errors_to_hash(@business)
        format.html { render :new }
        format.json { render json: errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    if @business.update(ParamsHelper.business_params(params))
      render json: BusinessDTO.instance_to_hash(@business), status: :ok
    else
      logger.warn "Trying to update business{#{@business.inspect}} resulted in errors: #{@business.errors.full_messages}"
      errors =  errors_to_hash(@business)
      render json: errors, status: :unprocessable_entity
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_tag
    business = current_user.business
    tag_id = tag_params[:id]

    business_tag = BusinessTag.new(:business_id => business.id, :tag_id => tag_id)

    if business_tag.save
      render json: SimpleDTO.instance_to_hash(business_tag.tag), status: :created
    else
      logger.warn "Trying to create business_tag{#{business_tag.inspect}} resulted in errors: #{business_tag.errors.full_messages}"
      errors =  errors_to_hash(business_tag)
      render json: errors, status: :unprocessable_entity
    end
  end

  def destroy_tag
    business = current_user.business
    tag_id = tag_params[:id]
    business_tag = BusinessTag.where({business_id: business.id, tag_id: tag_id}).first

    if business_tag.nil?
      render json: [], status: :not_found
    elsif business_tag.destroy
      render json: [], status: :no_content
    else
      logger.warn "Trying to destroy business_tag{#{business_tag.inspect}} resulted in errors: #{business_tag.errors.full_messages}"
      errors =  errors_to_hash(@business)
      render json: errors, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:id)
    end
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :biography %><br>
    <%= f.text_area :biography %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <!--Make this an ajax call against the tags controller-->
  <div class="eld">
    <%= f.label :business_tags %><br>
    <%= text_area_tag :business_tags, nil %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Businesses</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Company name</th>
      <th>Phone number</th>
      <th>Biography</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.user_id %></td>
        <td><%= business.company_name %></td>
        <td><%= business.phone_number %></td>
        <td><%= business.biography %></td>
        <td><%= business.website %></td>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New Business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @business.user_id %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @business.company_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @business.phone_number %>
</p>

<p>
  <strong>Biography:</strong>
  <%= @business.biography %>
</p>

<p>
  <strong>Website:</strong>
  <%= @business.website %>
</p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>