config/routes.rb
Rails.application.routes.draw do

  get 'dashboard', :to => 'dashboards#dashboard'

  get 'feedback/completed', :to => 'feedbacks#completed'
  resources :feedbacks
  get 'privacy_policy', :to => 'static_pages#privacy_policy'
  get 'static/map_data/', to: 'static_data#map_data'
  get 'static/captcha_key/', to: 'static_data#captcha_key'
  get 'static/eula/', to: 'static_data#get_eula'

  delete 'measurements/:id', to: 'measurements#destroy', as: 'measurements/destroy'

  post 'measurements/group/', to: 'measurements#create_group', as: 'measurements/group/create'
  put 'measurements/group/:id', to: 'measurements#update_group', as: 'measurements/group/update'
  delete 'measurements/group/:id', to: 'measurements#destroy_group', as: 'measurements/group/destroy'

  post 'terms_and_conditions/accept'
  get 'terms_and_conditions/has_accepted'
  get 'terms_and_conditions/show', :to => 'static_pages#terms_and_conditions'
  get 'terms_and_conditions', to: 'terms_and_conditions#show'

  devise_scope :user do
    get 'registration/completed/:id', to: 'users/registrations#completed', as: 'registration/completed'
    get 'profile', to: 'profiles#show'
    patch 'profile_picture', to: 'profiles#set_profile_picture'
  end

  resources :ratings
  get 'locations/mine', to: 'locations#my_locations'
  resources :locations

  resources :notifications
  resources :notification_templates

  resources :preferences
  patch 'preferences/user', to: 'preferences#update', as: 'user/preferences/update'

  resources :businesses
  post 'business/tag', to: 'businesses#create_tag', as: 'business/tag/create'
  delete 'business/tag', to: 'businesses#destroy_tag', as: 'business/tag/destroy'

  resources :pictures
  get 'landing_page/index', as: 'landing_page'

  resources :addresses
  devise_for :users, :controllers => {
      :confirmations => 'users/confirmations',
      :passwords => 'users/passwords',
      :registrations => 'users/registrations',
      :sessions => 'users/sessions',
      :unlocks => 'users/unlocks',
  }, :format => false
  resources :promo_codes
  resources :tags
  resources :quotes

  get 'purchases/completed', to: 'purchases#completed', :format => false
  get 'purchases/packages', to: 'purchases#list_packages'
  resources :purchases, :format => false, only: [:index, :new, :create, :show]

  get 'projects/mine', to: 'projects#my_projects', as: 'projects_mine'
  resources :projects, :format => false

  get 'estimates/mine', to: 'estimates#my_estimates', as: 'estimates_mine'
  resources :estimates

  resources :landing_page
  resources :quantifiers
  require 'resque-history/server'

  post 'projects/:id/spam' => 'projects#report_as_spam', as: 'project_report_as_spam'
  patch 'projects/:id/publish' => 'projects#publish', as: 'publish_project'
  patch 'projects/:id/cancel' => 'projects#cancel', as: 'cancel_project'
  patch 'projects/:id/accept/:estimate_id' => 'projects#accept_quote', as: 'accept_quote'
  get 'projects/search/lat/:lat/lng/:lng', to: 'projects#search', as: 'summaries_search', constraints: {lat: /[-\d.]*/, lng: /[-\d.]*/ }
  post 'projects/:id/tag', to: 'projects#create_tag', as: 'project/tag/create'
  delete 'project/:id/tag', to: 'projects#destroy_tag', as: 'project/tag/destroy'

  get 'tags/find_like_name/:name', to: 'tags#find_like_name', as: 'find_like_name'

  get 'ratings/get_business_ratings/:business_id', to: 'ratings#get_business_ratings'

  patch 'promo_code/:id/cancel' => 'promo_codes#cancel', as: 'cancel_promotion'
  get 'validate_promo_code', to: 'promo_codes#validate_promo_code', :format => false

  get 'user_landing_page', to: 'projects#index'
  get 'business_landing_page', to: 'projects#index'
  get 'admin_landing_page', to: 'tags#index'

  get 'account_search', to: 'business_centre#account_search'
  get 'business_search', to: 'business_centre#business_search'

  root 'landing_page#index'

end

app/views/layouts/shared/_beneficial.html.haml
.box-wrapper
  .image.section-image-3
  .box-container.bg-semi-white
    .container
      .box
        .box-heading
          %h2 Why is this beneficial?
        .box-body
          %p.text-center
            In this day and age, no one has time to waste, and when looking for quotes from companies, contractors, etc., it can be incredibly time-consuming and exasperating to schedule a time to meet with people just for estimation purposes.
            %br/
            There are several small to mid-sized jobs that do not require on-site inspections in order for a quote to be provided – and it is often the scheduling of the on-site inspections that are difficult, timely and inconvenient for both the consumer and contractor.
          .row
            .col-sm-6
              %p
                %b By eliminating unnecessary on-site inspections, contractors can:
              %ul
                %li Book jobs more quickly
                %li Invest less time providing quotes, and more time on the actual project at hand
                %li Increase productivity
                %li Compete with direct competition
                %li Advertise services online
            .col-sm-6
              %p
                %b By eliminating unnecessary on-site inspections, consumers can:
              %ul
                %li Compare competitive prices
                %li Compare contractors’ experience, knowledge, portfolio etc. right on the website
                %li Save time looking for estimations
                %li Get the job started and completed in a timely, efficient manner

app/views/layouts/shared/_footer.html.haml
%footer
  .container
    .row
      .col-sm-4
        .footer-links
          %h4 Company
          %ul.list-unstyled
            %li
              =link_to "Contact Us", new_feedback_path
            %li
              =link_to "Projects",projects_path
            %li
              =link_to "Blog","http://blog.quotr.ca/",:target=>'_blank'
            %li
              =link_to "Register",new_user_registration_path
            %li
              =link_to "Business Sign Up",new_user_registration_path({business: true})
            %li
              =link_to "Login",new_user_session_path
      .col-sm-4
        .footer-links
          %h4 Legal
          %ul.list-unstyled
            %li
              =link_to "Privacy Policy",privacy_policy_path
            %li
              =link_to "Terms & Conditions",terms_and_conditions_show_path
      .col-sm-4
        .footer-links
          %h4 Get Social
          %ul.social-links.list-inline
            %li
              =link_to 'http://www.facebook.com/QuotrSupport',:target=>'_blank',:title => "Like us on Facebook" do
                %i.fa.fa-facebook
            %li
              =link_to 'http://www.instagram.com/QuotrSupport',:target=>'_blank',:title => "Follow us on Instagram" do
                %i.fa.fa-instagram
  .copyright
    %p Copyright © 2016 Quotr. All rights reserved.

app/views/layouts/shared/_header.html.haml
%header.fixed-header
	.container-fluid
		.row.relative
			/ Mobile menu toggle button
			#showMobileMenu.menu-btn
				%i.fa.fa-bars
			/ /Mobile menu toggle button
			/ Header Social links
			.col-md-6.hidden-xs.hidden-sm
				%ul.social-links.list-inline
					%li
						=link_to 'http://www.facebook.com/QuotrSupport',:target=>'_blank',:title => "Like us on Facebook" do
							%i.fa.fa-facebook
					%li
						=link_to 'http://www.instagram.com/QuotrSupport',:target=>'_blank',:title => "Follow us on Instagram" do
							%i.fa.fa-instagram
			/ Header links
			.middle-link
				%ul.header-links.list-unstyled
					%li.hidden-xs
						=link_to "Projects",projects_path
					%li
						=link_to image_tag('logo-quotr.png',:alt => "quotr"),root_path,:class=>'logo'
					%li.hidden-xs
						=link_to "Blog","http://blog.quotr.ca/",:target=>'_blank'
			/ Header Right links
			.col-md-6.hidden-xs.hidden-sm
				%ul.right-links.list-inline
					-if user_signed_in? 
						%li
							.dropdown
								%a#notification.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "javascript:void(0);"}
									%i.fa.fa-bell
								%ul.dropdown-menu{"aria-labelledby" => "notification"}
									%li
										%a{:href => "#"} Lorem ipsum dolor sit amet
									%li
										%a{:href => "#"} Lorem ipsum dolor sit amet
									%li
										%a{:href => "#"} Lorem ipsum dolor sit amet
						%li
							.dropdown{:id =>'user_menu'}
								=link_to current_user.full_name,dashboard_path
								%ul.dropdown-menu
									%li
										=link_to "Dashboard",dashboard_path
									%li
										=link_to "Profile",edit_user_registration_path
									%li
										=link_to "Purchasing",purchases_path

						%li
							=link_to "Log Out",destroy_user_session_path,method: :delete,:class=>'btn btn-gold'
					-else
						%li
							=link_to "Register",new_user_registration_path
						%li
							=link_to "Business Sign Up",new_user_registration_path({business: true})
						%li
							=link_to "Log In",new_user_session_path,:class=>'btn btn-gold'
					/ shows after login

					/ /shows after login
			/ Notification shown on mobile
			-if user_signed_in? 
				.notification.pull-right.hidden-sm.hidden-md.hidden-lg
					.dropdown
						%a#notification.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "javascript:void(0);"}
							%i.fa.fa-bell
						%ul.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "notification"}
							%li
								%a{:href => "#"} Lorem ipsum dolor sit amet
							%li
								%a{:href => "#"} Lorem ipsum dolor sit amet
							%li
								%a{:href => "#"} Lorem ipsum dolor sit amet
				/ /Notification shown on mobile

app/views/layouts/shared/_how_does_it_work.html.haml
.box-wrapper
  .image.section-image-2
  .box-container.bg-semi-white
    .container
      .box
        .box-heading
          %h2 How does it work?
        .box-body
          %p.text-center
            Contractors are able to view prospective jobs and submit quotes based on the detailed information, description and pictures provided by the client via our site.
            %br/
            Prospective clients post what they’re looking for; contractors send over a quote. It’s truly that simple. Contractors will also have a profile to display experience, knowledge, past-projects, consumer ratings, etc. allowing them to separate themselves from their direct competition.

app/views/layouts/shared/_mobile_menu.html.haml
%aside
  .clearfix
    %h5.pull-left.m-t-5.m-b-3 Menu
    %span.pull-right.close-menu
      %i.fa.fa-times
  -if user_signed_in? 
    .user-name.clearfix
      =current_user.full_name
      %small.pull-right
        =link_to "Profile",edit_user_registration_path
    %ul.list-unstyled
      %li
        =link_to "Dashboard",dashboard_path
    %ul.list-unstyled
      %li
        =link_to "Purchasing",purchases_path

  %ul.list-unstyled
    -unless user_signed_in?
      %li
        =link_to "Register",new_user_registration_path
      %li
        =link_to "Business Sign Up",new_user_registration_path({business: true})
      %li
        =link_to "Log In",new_user_session_path
    %li
      =link_to "Projects",projects_path
    %li
      =link_to "Blog","http://blog.quotr.ca/",:target=>'_blank'
  -if @show_business_centre
    %h5 Business Centre
    %ul.list-unstyled
      %li
        =link_to "Account Search",account_search_path
      %li
        =link_to "Business Search",business_search_path
  %ul.list-unstyled
    %li
      =link_to "Contact Us",new_feedback_path
  -if user_signed_in?
    %ul.list-unstyled
      %li
        =link_to "Log Out",destroy_user_session_path,method: :delete
  / Social links
  %h5 Get Social
  %ul.social-links
    %li
      =link_to 'http://www.facebook.com/QuotrSupport',:target=>'_blank',:title => "Like us on Facebook" do
        %i.fa.fa-facebook
    %li
      =link_to 'http://www.instagram.com/QuotrSupport',:target=>'_blank',:title => "Follow us on Instagram" do
        %i.fa.fa-instagram
/ /Mobile Menu

app/views/layouts/shared/_purpose.html.haml
/ box-wrapper
.box-wrapper
  .image.section-image-1
  .box-container.bg-semi-white
    .container
      .box
        .box-heading
          %h2 What is the purpose?
        .box-body
          %p.text-center
            The website is designed to simplify the process of delivering/receiving quotes. It eliminates the rigmarole that comes with finding contractors to receive an estimate on a project.

app/views/layouts/shared/_temporary_links.html.haml
.bg-white.sub-links.hidden-xs
  .container-fluid.clearfix
    %ul.list-inline.pull-left
      %li
        =link_to "Businesses",businesses_path
      %li
        =link_to "Addresses", addresses_path 
      %li
        =link_to "Locations",locations_path
      %li
        =link_to "Estimates",estimates_path
      %li
        =link_to "Pictures",pictures_path
      %li
        =link_to "Purchases",purchases_path
      %li
        =link_to "Promo Codes",promo_codes_path
      %li
        =link_to "Tags",tags_path
      %li
        =link_to "Preferences",preferences_path
    -if @show_business_centre
      %ul.list-inline.pull-right
        %li
          =link_to "Account Search",account_search_path
        %li
          =link_to "Business Search",business_search_path